version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ checksum ".ruby-version" }}-

      - run:
          name: Install dependencies
          command: bundle check || bundle install --jobs=4 --retry=3

      - save_cache:
          key: gem-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run: bundle exec rspec
